config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "applicants#index"

  get '/:id', to: 'applicants#show', as: :applicant
  put '/:id', to: 'applicants#update'
  get '/applicants', to: 'applicants#index', as: :applicants
  post '/applicants', to: 'applicants#create'

  post '/applicants/:applicant_id/notes', to: 'notes#create', as: :notes
  delete '/applicants/:applicant_id/notes/:id', to: 'notes#destroy', as: :note

  post '/applicants/:applicant_id/attachments', to: 'attachments#create', as: :attachments
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :notes, dependent: :destroy
  has_many :attachments, dependent: :destroy

  before_save :cleanup_attributes

  private

  def cleanup_attributes
    self.attributes.each do |attribute, value|
      next unless value.is_a?(String)

      value = value.strip.upcase unless value.blank?
      self.send("#{attribute}=", value)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :applicant
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :applicant
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :applicants

  before_save :cleanup_attributes

  def cleanup_attributes
    self.attributes.each do |attribute, value|
      next unless value.is_a?(String)

      value = value.strip.upcase unless value.blank?
      self.send("#{attribute}=", value)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :applicants
  has_many :tags

  enum tier: [:trial, :free, :premium]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :fetch_or_create_user
  before_action :set_current_user_tags, only: %i[index]
  before_action :set_applicant, only: %i[update show]

  def index
    handle_filters

    @applicants =
      current_user
        .applicants
        .left_joins(:tags)
        .where(tags_are_selected)
        .order(params[:order] || { created_at: :desc })
        .page(params[:page])
        .having(filtered_tags_having_clause)
        .group("applicants.id")
  end

  def create
    @applicant =
      current_user.applicants.create(
        name: params[:name],
        summary: params[:summary],
        rating: params[:rating],
        phone: params[:phone],
        email: params[:email],
        website: params[:website],
        location: params[:location],
        tags:
          processed_tags.map do |tag_name|
            Tag.find_or_initialize_by name: tag_name.strip.upcase,
                                      user: current_user
          end,
      )

    redirect_to root_path
  end

  def update
    add_tag
    remove_tag
    # update_applicant
    render 'update.js.erb'
  end

  def show;end

  private

  def processed_tags
    params[:tags].split(",")
  end

  def handle_filters
    session[:tags_to_filter] ||= []
    session[:tags_to_filter] |= [params[:add_tag]] if params[:add_tag].present?
    if params[:remove_tag].present?
      session[:tags_to_filter].delete params[:remove_tag]
    end
    session[:tags_to_filter].compact!
  end

  def tags_are_selected
    return unless session[:tags_to_filter].present?

    { tags: { name: session[:tags_to_filter] } }
  end

  def filtered_tags_having_clause
    return unless session[:tags_to_filter].present?

    "COUNT(DISTINCT tags.name) = #{session[:tags_to_filter].count}"
  end

  def add_tag
    return unless params[:add_tag].present?

    @added_tag = Tag.find_or_initialize_by name: params[:add_tag].strip.upcase,
                                    user: current_user

    if @applicant.tags.include? @added_tag
      @added_tag = nil
    else
      @applicant.tags << @added_tag
      @applicant.save
    end
  end

  def remove_tag
    return unless params[:remove_tag].present?

    @removed_tag = @applicant.tags.find_by_name(params[:remove_tag])
    @applicant.tags.destroy(@removed_tag.id) if @removed_tag.present?
  end

  def set_applicant
    @applicant = current_user.applicants.find(params[:id])
  end

  def set_current_user_tags
    @current_user_tags = current_user.tags.joins(:applicants).group("tags.id")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def fetch_or_create_user
    current_user ||
      sign_in(
        User.create(
          email: "#{SecureRandom.uuid}@tmp.com",
          password: SecureRandom.hex
        )
      )
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_applicant
  before_action :set_attachment, only: %i[]

  def create
    upload = Cloudinary::Uploader.upload(params[:content], folder: 'ats_app')
    @applicant.attachments.create(
      url: upload["secure_url"],
      filename: params[:content].original_filename,
      json_data: upload.to_json
    )

    redirect_to applicant_path @applicant
  end

  # def destroy
  #   @attachment.destroy

  #   render 'destroy.js.erb'
  # end

  private

  def set_applicant
    @applicant = current_user.applicants.find params[:applicant_id]
  end

  def set_attachment
    @attachment = @applicant.attachments.find params[:id]
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  include ActionView::Helpers::DateHelper

  before_action :fetch_or_create_user
  before_action :set_player

  def show
    cookies[:start_time] ||= { :value => Time.now, :expires => 99.days.from_now }

    return render_game_over if @player.beat_spells.count >= 648

    set_spell
  end

  def win
    BeatSpell.create(spell_id: params[:spell_id], player: @player)
    head :ok
  end

  def reset
    @player.beat_spells.destroy_all
    cookies[:start_time] = Time.now
    cookies.delete(:end_time)

    redirect_to root_path
  end

  private

  def set_spell
    @spell = Spell.where(
      id: Spell.where.not(id: @player.beat_spells.pluck(:spell_id))
               .pluck(:id).sample
    ).first
  end

  def render_game_over
    cookies[:end_time] ||= { :value => Time.now, :expires => 99.days.from_now }
    @time_to_complete = distance_of_time_in_words(cookies[:start_time], cookies[:end_time])
    render :game_over
  end

  def set_player
    @player = Player.find_by(id: cookies[:player_id]) || Player.create
    cookies[:player_id] ||= { :value => @player.id, :expires => 99.days.from_now }
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_applicant
  before_action :set_note, only: %i[destroy]

  def create
    @applicant.notes.create(content: params[:content])

    redirect_to applicant_path @applicant
  end

  def destroy
    @note.destroy

    render 'destroy.js.erb'
  end

  private

  def set_applicant
    @applicant = current_user.applicants.find params[:applicant_id]
  end

  def set_note
    @note = @applicant.notes.find params[:id]
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/views/applicants/index.html.erb
<%= form_with url: applicants_path, method: :post do |f| %>
  <div class="form-row">
   <h4>Add New Talent</h2>
  </div>

  <div class="form-row d-flex">
    <div class="form-group col-4 p-1">
      <%= f.text_field :name,
                       autocomplete: :off,
                       autofocus: true,
                       class: 'form-control',
                       placeholder: 'Name',
                       required: true,
                       minlength: 2 %>
    </div>

    <div class="form-group col-7 p-1">
      <%= f.text_field :tags,
                       autocomplete: :off,
                       class: 'form-control',
                       placeholder: 'Tags (ex.: ruby, vue, node, senior)' %>
    </div>

    <div class="form-group col-1 p-1">
      <%= f.submit 'Add', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<hr>

<h4>Talent List</h2>

<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Rating</th>
  </tr>
  </thead>
  <tbody>
  <% @applicants.each do |applicant| %>
  <tr>
    <th scope="row">
      <%= link_to applicant.name&.truncate(20), applicant_path(applicant.id) %>
      <span class="fw-normal small">
        <% applicant.tags.each.with_index do |tag, i| %>
          <span class="badge bg-secondary"><%= tag.name %></span>
        <% end %>
      </span>
    </th>
    <td><%= applicant.rating %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<% if @applicants.blank? %>
  <div>
    You have no Talents yet
  </div>
<% end %>

<%= paginate @applicants %>

app/views/applicants/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <div class="card card-primary card-outline">
        <div class="card-body box-profile">
          <h3 class="profile-username text-center"><%= @applicant.name %></h3>

          <h5>Tags</h5>
          <div id="tags-box" class="my-2">
            <% @applicant.tags.each.with_index do |tag, i| %>
              <%= link_to applicant_path(id: @applicant.id, remove_tag: tag.name), method: :put, remote: true do %>
                <span
                  class="badge bg-secondary tag-remove"
                  data-tagname="<%= tag.name %>"><%= tag.name %>
                    <span
                      class="fw-lighter text-decoration-underline">x</span></span><% end %>
            <% end %>
          </div>
          <%= form_with url: applicant_path(@applicant), method: :put, remote: true, id: :add_tag_form do |f| %>
            <%= f.text_field :add_tag,
                             class: 'form-control',
                             placeholder: 'Add Tag',
                             autocomplete: :off,
                             pattern: '[a-zA-Z0-9 #.+]+',
                             require: true,
                             id: :add_tag_input,
                             data: { :disable_with => "Adding tag..." } %>
          <% end %>
        </div>
      </div>

      <hr>

      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Attachments</h3>
        </div>

        <div class="card-body">
          <%= form_with url: attachments_path(applicant_id: @applicant.id), method: :post, id: 'attachment_upload_form' do |f| %>
            <%= f.file_field(:content, id: 'attachment_upload_field') %>
          <% end %>

          <% @applicant.attachments.each do |attachment| %>
            <div class="my-1"><strong><i class="fas fa-file"></i> <%= attachment.filename %></strong></div>
          <% end %>
        </div>
      </div>

      <hr>

      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Appointments</h3>
        </div>

        <div class="card-body">
          <div class="my-1"><strong><i class="fas fa-file"></i> cv.pdf</strong></div>
          <div class="my-1"><strong><i class="fas fa-file"></i> id.pdf</strong></div>
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="card">
        <div class="card-header p-2">
          <ul class="nav nav-pills">
            <li class="nav-item">
              <a class="nav-link active" href="#activity" data-toggle="tab"
                >Notes</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#timeline" data-toggle="tab"
                >Attachments</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#settings" data-toggle="tab"
                >Appointments</a
              >
            </li>
          </ul>
        </div>

        <div class="card-body">
          <div class="tab-content">
            <div class="active tab-pane" id="activity">
              <%= form_with url: notes_path(applicant_id: @applicant.id), method: :post, id: :note_create_form do |f| %>
                <%=
                  f.text_field :content,
                              class: 'form-control',
                              placeholder: 'Type a Note',
                              required: true,
                              autocomplete: :off,
                              minlength: 2 %>
                <%= f.submit 'Add Note',
                             class: 'mt-1 btn btn-primary',
                             data: { :disable_with => "Adding Note..." } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

    <% @applicant.notes.order(created_at: :desc).each do |note| %>
      <div class="post card my-1" id="note-card-<%= note.id %>">
        <div class="card-body px-3 py-2">
          <p class="m-0">
            <%= note.content %>
          </p>
          <p class="mb-0 text-secondary">
            <span class="small"
              ><%= note.created_at.strftime('%c %Z') %></span>
            <%=
              link_to 'Delete',
                      note_path(applicant_id: @applicant.id, id: note.id),
                      method: :delete,
                      remote: true,
                      class: 'btn btn-outline-danger btn-sm',
                      data: { :disable_with => "Deleting..." } %>
          </p>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#add_tag_form").bind("ajax:beforeSend", function(event,xhr,status) {
    $('#add_tag_input').val('');
  });

  document.getElementById("attachment_upload_field").onchange = function() {
    document.getElementById("attachment_upload_form").submit();
  };
</script>

app/views/applicants/update.js.erb
<% if @removed_tag.present? %>
  $("[data-tagname=\"<%= @removed_tag.name.html_safe %>\"").remove();
<% end %>

<% if @added_tag.present? %>
  $("#tags-box").append('<a data-remote="true" rel="nofollow" data-method="put" href="/<%= @applicant.id %>?remove_tag=<%= @added_tag.name %>"><span class="badge bg-secondary tag-remove" data-tagname="<%= @added_tag.name %>"><%= @added_tag.name %> <span class="fw-lighter text-decoration-underline">x</span></span></a> ');
  $("#add_tag_input").val('');
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
  <% if current_page?({controller: :applicants, action: :index}) %>
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-5">Filters</span>
    </a>
    <hr>

    <div class="form-row d-flex mb-1">
      <div class="form-group col-12">
        <div class="d-block">
          <%= form_with url: root_path, method: :get, id: 'add-tag-filter-form' do %>
            <input name="add_tag" class="form-control" id="tag-select" placeholder="Filter by Tags">
          <% end %>
        </div>
      </div>
    </div>

    <div>
      <% session[:tags_to_filter].each do |tag| %>
        <%= link_to root_path(remove_tag: tag) do %>
          <span
            style="cursor: pointer;"
            data-tagname="<%= tag %>"
            class="badge bg-secondary tag-remove"><%= tag %> <span class="fw-lighter text-decoration-underline">x</span></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  <% if current_page?({controller: :applicants, action: :index}) %>
    $("#tag-select").autocomplete({
      source: <%= @current_user_tags.map { |tag| tag.name }.to_s.html_safe %>,
      select: (event, ui) => {
        $("#tag-select").val(ui.item.value);
        $("#add-tag-filter-form").submit();
      }
    });

    $('#tag-select').on('keyup keypress', function(e) {
      var keyCode = e.keyCode || e.which;
      if (keyCode === 13) { 
        e.preventDefault();
        return false;
      }
    });
  <% end %>
</script>

app/views/layouts/_topbar.html.erb
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-2 px-3">
  <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
  </a>

  <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
    <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
    <li><a href="/" class="nav-link px-2 link-dark">Features</a></li>
    <li><a href="/" class="nav-link px-2 link-dark">Pricing</a></li>
    <li><a href="/" class="nav-link px-2 link-dark">FAQs</a></li>
    <li><a href="/" class="nav-link px-2 link-dark">About</a></li>
  </ul>

  <div class="col-md-3 text-end">
    <% if current_user.trial? %>
      <button type="button" class="btn btn-outline-primary me-2">Login</button>
      <button type="button" class="btn btn-primary">Sign-up</button>
    <% else %>
      <p class="alert"><%= current_user.email %></p>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ATS App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'favicon.png' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="bg-light">
    <%= render('layouts/topbar') %>

    <% if notice %><p class="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert"><%= alert %></p><% end %>

    <main class="d-flex">
      <%= render('layouts/sidebar') %>
      <div class="d-flex flex-column w-100">
        <%= yield %>
      </div>
    </main>

  </body>
</html>

app/views/notes/destroy.js.erb
$('#note-card-<%= @note.id %>').remove();